---
# buff_spells example:
#  Instinct:
#    abbrev: inst
#    recast: 1
#    mana: 10
#    cambrinth:
#    - 5
#    - 5
# Supported configuration options:
#   abbrev: the spell abbreviation, or spell name if it does not have an abbreviation
#   recast: the time remaining on a buff before recasting it; -1 means to let it fade
#   mana: the amount to harness (via attunement)
#   cambrinth: an array of charge amounts; [5, 5] would charge your cambrinth by 5 mana twice

# offensive_spells example:
# - skill: Debilitation
#   name: Devolve
#   abbrev: de
#   mana: 14
#   expire: which evaporate quickly into the air
#   harmless: true
# Supported configuration options:
#   skill: the skill this spell trains; the script prioritizes skills with lower field exp
#   name: the spell name
#   abbrev: the spell abbreviation, or spell name if it does not have an abbreviation
#   mana: the amount to harness (via attunement)
#   expire: text which will trigger recasting the spell
#   harmless: indicates the spell is can be cast while dancing
#   cast: custom action to output instead of 'cast'
#   after-message: action to take after the spell has been cast
#   after-matches: text to watch for which indicates completion of the action

# training_spells example:
#  Utility:
#    abbrev: blend
#    after:
#    - message: release blend
#      matches:
#      - You fade into view
# Supported configuration options:
#   abbrev: the spell abbreviation, or spell name if it does not have an abbreviation
#   symbiosis: whether or not to use chaos symbiosis
#   before-message: action to take before the spell is cast
#   before-matches: text to watch for which indicates completion of the action
#   cast: custom action to output instead of 'cast'
#   after-message: action to take after the spell has been cast
#   after-matches: text to watch for which indicates completion of the action

# moves to use to fill time while aiming
# stops as soon as best shot possible is seen
aim_fillers:
  Crossbow:
  - bob
  - bob
  Bow:
  - bob
  - bob
  - bob
  Slings:
  - bob
  - bob
  - bob
lootables:
# things to pick up off the ground
# ammunition
- bolt
- arrow
- rock
# valuable loot
- coin
- map
- scroll
- bark
- parchment
# gems
- tsavorite
- zircon
- quartz
- chalcedony
- diopside
- coral
- moonstone
- onyx
- topaz
- amber
- pearl
- chryso
- lazuli
- turquoise
- bloodstone
- hematite
- morganite
- sapphire
- agate
- carnelian
- diamond
- crystal
- emerald
- ruby
- tourmaline
- tanzanite
- jade
- ivory
- sunstone
- iolite
- beryl
- garnet
- alexandrite
- amethyst
- citrine
- aquamarine
- star-stone
- crystal
- kunzite
- stones
- spinel
- opal
- peridot
- andalusite

#items to throw away without warning
trash_nouns:
- leaf
- pestle
- mortar
- label
- runestone
- flower
- flowers
- arrowhead
- root
- stem
- grass
- needle
- sap
- glue
- hilt
- thread
- flint
- nugget
- dira
- stems
- leaves
- bar
- lotion

stances:
# custom stances to prevent trying to parry with ranged weapons
  Bow:
  - evasion
  - shield
  Crossbow:
  - evasion
  - shield
  Slings:
  - evasion
  - shield
  Offhand Weapon:
  - evasion
  - shield
skinning:
# skinning behavior. If you don't wear a bundle skins will drop to the ground
  skin: true
  arrange_all: false
  arrange_count: 0
# what cambrinth do you wear and how much does it hold
cambrinth: armband
cambrinth_cap: 32
# do you need to hold it to charge it?
held_cambrinth: false
# If you cast spells for training make sure their prep and cast messages are
# recorded here
cast_messages:
- ^You gesture
- You reach with both
- You listen intently to the air
- You close your eyes
- You close yours eyes
- Your target pattern dissipates
- You make a holy gesture
- You raise your left hand skyward
- Flickering shadows tear away
- You sense a Malediction
- You release an accompaniment
- You roll your hands in an elliptical pattern
- You cup your hand
prep_messages:
- You begin chanting a psalm
- With (calm|meditative|rigid|tense) movements you
- You raise your head skyward
- With (tense|calm) movements
- You trace (an|a) (.*) sigil in the air
- Slow, rich tones form
- You begin chanting( a)? (catechisms|mantra|prayer|psalm)
- You raise (your|an) (arm|arms|head|palms) skyward
- With a sharp cut to your voice
- With a resounding "POP"

khri_preps:
- With deep breaths
- Centering your mind
- Focusing your mind
- Remembering the mantra of
- Turning inwards, you find the
- Darkness is no bar to a
- Taking a deep breath
- Placing all of your thoughts
- Your hand twitches slightly
- With but a quick thought
- You calm your body and mind
- Letting your thoughts fall into
charged_maneuvers:
  Brawling: palmstrike
  Bow: powershot
  Crossbow: powershot
  Slings: powershot
  Small Edged: cleave
  Large Edged: cleave
  Twohanded Edged: cleave
  Small Blunt: crash
  Large Blunt: crash
  Twohanded Blunt: crash
  Staves: twirl
  Polearms: impale
# Number of enemies to let build up before trying to kill them
dance_threshold: 0
# weapon skill to use while dancing
dance_skill: Small Edged
# actions to use while dancing
dance_actions:
- analyze
- feint
- bob
# abilities to train while fighting and their cooldown in seconds
training_abilities:
  Hunt:
    :check: Perception
    :cooldown: 80
fatigue_regen_threshold: 90
fatigue_regen_action: bob
# cooldown timers between attempts to train a skill
# TODO remove timer field and store in uservars
exp_timers:
  Stealth:
    cooldown: 300
  First Aid:
    cooldown: 360
  Locksmithing:
    cooldown: 600
  Theurgy:
    cooldown: 720
  Thievery:
    cooldown: 3600
  Attunement:
    cooldown: 130
  Summoning:
    cooldown: 120
# this scaling factor is multiplied by your discerned max mana for a spell
# it rounds up so anything < 1.0 will always result in one mana removed
prep_scaling_factor: 0.98
# listen to classes?
listen: true

forge_container: backpack
forge_hammer: diagonal-peen

armor_container: backpack

safe_room: 851

hide_to_steal: true

# what to remove for braiding
hand_armor: gloves

# should crossing training idle or exit when all skills are above 28/34?
exit_on_skills_capped: false

# Lockpicking settings for pick.lic
stop_pick_on_mindlock: true
use_lockpick_ring: true
lockpick_type: ordinary
harvest_traps: true
picking_box_source: duffel bag
picking_box_storage: backpack

hunting_zones:
  rats:
  - 6049
  - 6048
  - 6047
  - 6046
  - 6050
  - 6053
  - 6054
  louts:
  - 686
  - 687
  - 688
  - 19199
  - 690
  hogs:
  - 1438
  - 1439
  - 1440
  - 1441
  - 1442
  - 1443
  - 1444
  - 1445
  - 1446
  - 1447
  - 1448
  goblins:
  - 1473
  - 1479
  - 1483
  - 1486
  - 1484
  - 1480
  scouts: # This is about half of the area
  - 7292
  - 7293
  - 7294
  - 7295
  - 7296
  - 7297
  - 7298
  - 7299
  reavers:
  - 1850
  - 1851
  - 1852
  - 1856
  - 1848
  - 1849
  rock_trolls:
  - 8946
  - 8947
  - 8954
  - 8955
  - 8948
  - 8949
  snowbeasts: # 2264 causes a loop, do not use
  - 2255
  - 2268
  - 2263
  - 2256
  - 2265
  - 2266
  - 2272
  - 2259
  - 2260
  - 2262
  - 2267
  - 2269
  - 2270
  - 2261
  young_ogres:
  - 1588
  - 1591
  - 1592
  - 1593
  - 1590
  - 1589
  - 1587
  dire_bears: # 1555 is bugged, do not use
  - 1563
  - 1565
  - 1582
  - 1581
  - 1578
  - 1566
  pale_gray_spirits:
  - 19384
  - 19387
  - 19390
  - 19393
picking_box_storage: backpack

# Repair settings
repair_withdrawal_amount: 10_000

# Training-manager settings:
# Items to take from the safe room
safe_room_loot:
# Items to deposit in the safe room
safe_room_drop:
# The threshold (in copper) at which point you will deposit money with the empath on duty in the safe room
safe_room_deposit_threshold: 50_000
# The amount to deposit if you are above the threshold
safe_room_deposit_amount:
# The empath on duty in the safe room
safe_room_empath:
